const peliculas = {
    accion: [
        { id: 1, nombre: "John Wick 4", descripcion: "Keanu Reeves vuelve como el asesino retirado en esta cuarta entrega de la franquicia.", pais: "USA", imagen: "https://play-lh.googleusercontent.com/5efxbApfVAa9R1fStcVvSHqDhyXI40jLCd78b2NEuqNcC0McWceLAQGYnz0rFKZz7lywTdKNzfsXidP97A", estreno: false, valoracion: 4.1  },
        { id: 2, nombre: "El Escuadrón Suicida", descripcion: "Relanzamiento de Escuadrón Suicida con personajes de DC Cómics.", pais: "USA", imagen: "https://m.media-amazon.com/images/S/pv-target-images/86c00026ca61fabf6a06f028a628fd13106fad507650b43ccd81b0ef6aa7c400.jpg", estreno: true, valoracion: 4.0  },
        { id: 3, nombre: "La guerra del mañana", descripcion: "En un futuro cercano, la humanidad lucha contra alienígenas invasores.", pais: "USA", imagen: "https://es.web.img2.acsta.net/pictures/21/05/26/17/45/4238572.jpg", estreno: false, valoracion: 3.7  },
        { id: 4, nombre: "Fast & Furious 9", descripcion: "Dominic Toretto enfrenta su pasado y a su hermano en esta novena entrega.", pais: "USA", imagen: "https://images.justwatch.com/poster/307500313/s718/fast-y-furious-9.jpg", estreno: true, valoracion: 3.6  },
        { id: 5, nombre: "Viuda Negra", descripcion: "Natasha Romanoff resuelve asuntos pendientes de su pasado.", pais: "USA", imagen: "https://lumiere-a.akamaihd.net/v1/images/image_09cd2a64.jpeg?region=0,0,540,810", estreno: false, valoracion: 3.6  },
        { id: 6, nombre: "Misión: Imposible - Dead Reckoning", descripcion: "Ethan Hunt y su equipo enfrentan una inteligencia artificial llamada 'La Entidad'.", pais: "USA", imagen: "https://i0.wp.com/plexmx.info/wp-content/uploads/2023/06/mission_impossible__dead_reckoning_part_one_ver3_xlg.jpg?ssl=1", estreno: true, valoracion: 4.0  },
        { id: 7, nombre: "Transformers: El despertar de las bestias", descripcion: "Precuela de Transformers donde los Autobots se unen a los Maximals.", pais: "USA", imagen: "https://www.caminosalkantay.com/blog/wp-content/uploads/2023/06/Transformers-despertar-bestias-693x1024.jpg", estreno: false, valoracion: 3.0  },
        { id: 8, nombre: "Los Juegos del Hambre: Balada de pájaros cantores y serpientes", descripcion: "Precuela de Los Juegos del Hambre centrada en Corolianus Snow.", pais: "USA", imagen: "https://img.asmedia.epimg.net/resizer/v2/ORMROYWVCJHMLKQ6TGA3USQ53A.jpg?auth=c6eee79f57dc40b6d1ce7f6d5966034fdfe00ae1c9ba3e616a234cab19f40789&width=1200&height=1200&smart=true", estreno: true, valoracion: 4.0  },
        { id: 9, nombre: "Indiana Jones y el Dial del Destino", descripcion: "Indiana Jones se enfrenta a un ex jefe nazi en una trama de alunizaje.", pais: "USA", imagen: "https://musicart.xboxlive.com/7/7e306700-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080", estreno: false, valoracion: 3.7  },
        { id: 10, nombre: "Fast & Furious X", descripcion: "Décima entrega de la saga Fast & Furious con Dom enfrentando nuevos desafíos.", pais: "USA", imagen: "https://www.fastxmovie.com/images/main/mobile_bg.jpg?id=1716594846", estreno: true, valoracion: 3.0  }
      
    ],
    comedia: [
        { id: 1, nombre: "The Hangover", descripcion: "Tres amigos se despiertan de una despedida de soltero en Las Vegas sin recordar nada de la noche anterior.", pais: "USA", imagen: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p192248_p_v8_am.jpg", estreno: false, valoracion: 7.7 },
        { id: 2, nombre: "Superbad", descripcion: "Dos amigos inseparables en su último año de instituto intentan organizar una fiesta épica antes de separarse para ir a la universidad.", pais: "USA", imagen: "https://cafeanimelair.com/wp-content/uploads/2021/01/superbad-1.jpg", estreno: true, valoracion: 7.6 },
        { id: 3, nombre: "Step Brothers", descripcion: "Dos hermanos desempleados de mediana edad son obligados a vivir juntos cuando sus padres se casan.", pais: "USA", imagen: "https://media.themoviedb.org/t/p/w500/wRR6U3K3v2iQsG3uw7ehz1ctRyT.jpg", estreno: false, valoracion: 6.9},
        { id: 4, nombre: "Anchorman", descripcion: "Ron Burgundy es el presentador de noticias más famoso de San Diego en los años 70.", pais: "USA", imagen: "https://m.media-amazon.com/images/S/pv-target-images/2b8f0ca981efa664bf0d4969c028b54bc79c5bb3a285ae49883cfc0eeb9dc576.jpg", estreno: true, valoracion: 7.2},
        { id: 5, nombre: "Zombieland", descripcion: "Un estudiante tímido, un tipo duro en busca del último Twinkie y dos hermanas intentan llegar a un parque de atracciones en medio de un apocalipsis zombi.", pais: "USA", imagen: "https://es.web.img3.acsta.net/pictures/16/02/24/15/34/466376.jpg", estreno: false, valoracion: 7.6 },
        { id: 6, nombre: "Borat", descripcion: "Un reportero de Kazajistán es enviado a Estados Unidos para hacer un reportaje sobre el país más grande del mundo.", pais: "USA", imagen: "https://upload.wikimedia.org/wikipedia/en/3/39/Borat_ver2.jpg", estreno: true, valoracion: 7.3 },
        { id: 7, nombre: "Dumb and Dumber", descripcion: "Las aventuras de dos amigos de buen corazón pero increíblemente tontos en un viaje a través del país.", pais: "USA", imagen: "https://m.media-amazon.com/images/S/pv-target-images/7abea7c6df632663dc230c445f89da93c1623e0749166c77d5d764c475804905.jpg", estreno: false, valoracion: 7.3 },
        { id: 8, nombre: "Groundhog Day", descripcion: "Un meteorólogo se encuentra inexplicablemente viviendo el mismo día una y otra vez.", pais: "USA", imagen: "https://musicart.xboxlive.com/7/a2fe1100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080", estreno: true, valoracion: 8.0 },
        { id: 9, nombre: "Bridesmaids", descripcion: "La competencia entre la dama de honor y una de las damas de honor amenaza con arruinar la vida de una pastelera desempleada.", pais: "USA", imagen: "https://resizing.flixster.com/2eAI_qV48YK0qV3hOpimm45MF0I=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8414185_p_v8_ae.jpg", estreno: false, valoracion: 6.8 },
        { id: 10, nombre: "The Grand Budapest Hotel", descripcion: "Un escritor conoce al propietario de un hotel de alta clase envejecido, quien le cuenta sobre sus años de juventud como botones.", pais: "USA", imagen: "https://i.scdn.co/image/ab67616d0000b273afda2a51e7bb55197fdeb4c0", estreno: true, valoracion: 8.1 }
    ],
    terror: [
        { id: 1, nombre: "The Exorcist", descripcion: "Cuando una niña es poseída por una entidad misteriosa, su madre busca la ayuda de dos sacerdotes para salvarla.", pais: "USA", imagen: "https://cdn2.penguin.com.au/covers/original/9781407056692.jpg", estreno: false, valoracion: 8.0 },
        { id: 2, nombre: "Hereditary", descripcion: "Una familia en duelo es atormentada por eventos trágicos y perturbadores.", pais: "USA", imagen: "https://play-lh.googleusercontent.com/FQM-r3asbVHGqBdTn1NwTvsozb_ArgwDaQCVnmshGRGMCQu2XiV5Up7zgs0pUpsXwFDvkVwH0ki3_1Af3WU", estreno: true, valoracion: 7.3 },
        { id: 3, nombre: "A Nightmare on Elm Street", descripcion: "Los adolescentes son aterrorizados por Freddy Krueger, un antiguo asesino de niños que invade sus sueños.", pais: "USA", imagen: "https://play-lh.googleusercontent.com/P8zi7IbMEjJiCboRrtNUnndArXpxlVazF1Rds2dOn8_GTd7Nt59ots3JTVGBHhvNaxUoCw=w240-h480-rw", estreno: false, valoracion: 7.5 },
        { id: 4, nombre: "The Shining", descripcion: "Una familia se dirige a un hotel aislado donde una presencia siniestra influye en el padre para que se vuelva violento.", pais: "USA", imagen: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p40_p_v8_ar.jpg", estreno: true, valoracion: 8.4 },
        { id: 5, nombre: "Get Out", descripcion: "Un joven afroamericano visita a los padres de su novia blanca durante el fin de semana, donde su incomodidad inicial sobre la recepción se convierte en algo mucho más inquietante.", pais: "USA", imagen: "https://www.uphe.com/sites/default/files/styles/scale__319w_/public/2017/04/GetOut_800x1200.webp?itok=9nOS2EwB", estreno: false, valoracion: 7.7 },
        { id: 6, nombre: "The Conjuring", descripcion: "Los investigadores paranormales Ed y Lorraine Warren trabajan para ayudar a una familia aterrorizada por una oscura presencia en su granja.", pais: "USA", imagen: "https://play-lh.googleusercontent.com/SWkA0rhB0_kQ7TJSHUMxLLDCVIamxicbeq2fexEM0w8_Hlr63YefIVrI1OrjG3_RtpgcClx4jxzF3yvL4pzU", estreno: true, valoracion: 7.5 },
        { id: 7, nombre: "It", descripcion: "Un grupo de niños acosados se unen para destruir a un monstruo cambiante que se disfraza de payaso.", pais: "USA", imagen: "https://i.pinimg.com/originals/ba/9b/25/ba9b254a9a7d4377e370f48f98978b22.jpg", estreno: false, valoracion: 7.3 },
        { id: 8, nombre: "The Ring", descripcion: "Una periodista debe investigar una cinta de video misteriosa que parece causar la muerte de quien la ve en una semana.", pais: "USA", imagen: "https://m.media-amazon.com/images/I/5149w8Z530L._AC_UF894,1000_QL80_.jpg", estreno: true, valoracion: 7.1 },
        { id: 9, nombre: "The Babadook", descripcion: "Una madre soltera y su hijo caen en una profunda paranoia cuando un libro infantil titulado 'Mister Babadook' se manifiesta en su hogar.", pais: "Australia", imagen: "https://upload.wikimedia.org/wikipedia/en/d/d7/The-Babadook-Poster.jpg", estreno: false, valoracion: 6.8},
        { id: 10, nombre: "Paranormal Activity", descripcion: "Después de mudarse a una casa suburbana, una pareja se ve cada vez más perturbada por una presencia demoníaca nocturna.", pais: "USA", imagen: "https://m.media-amazon.com/images/M/MV5BZDk3OWEzZTktZjZiMy00OTYyLTk4NWMtNmYyMzY5YWZmMGZjXkEyXkFqcGdeQXVyMTM1MDExOTE2._V1_.jpg", estreno: true, valoracion: 6.3 }
    ],
};

export default peliculas;
